// Centralized Constants & Rule Definitions for ARGUS

export const ENTITY_NAMES = {
  "CSE-ALPHA": "CSE Alpha",
  "CSE-BETA": "CSE Beta",
  "CSE-GAMMA": "CSE Gamma",
};

export const ENTITY_SECTORS = {
  "CSE-ALPHA": "Power Grid / Critical Infrastructure",
  "CSE-BETA": "Grid Transmission & Dispatch",
  "CSE-GAMMA": "Nuclear Infrastructure & Control",
};

export const FEATURE_DEFINITIONS = [
  {
    num: 1,
    id: "execution-gaps",
    name: "Execution Gaps",
    tagline: "Unescalated serious alerts & premature closures",
    helper: "Did the SOC follow documented escalation policy for serious alerts?",
    desc: "Examines whether High and Critical severity alerts received the required supervisor escalation and diagnostic investigation before case closure.",
    iconName: "ShieldAlert",
    gradient: "from-amber-500/20 to-orange-500/5",
    borderGlow: "group-hover:border-amber-500/60",
    accentColor: "amber",
  },
  {
    num: 2,
    id: "negative-space",
    name: "Negative Space",
    tagline: "Monitoring blind spots & missing process records",
    helper: "What expected evidence is missing from our visibility?",
    desc: "Identifies designated critical assets producing zero monitoring telemetry and documented operational processes lacking case evidence.",
    iconName: "EyeOff",
    gradient: "from-cyan-500/20 to-blue-500/5",
    borderGlow: "group-hover:border-cyan-500/60",
    accentColor: "cyan",
  },
  {
    num: 3,
    id: "incident-reconstruction",
    name: "Incident Reconstruction",
    tagline: "Correlated multi-factor alert chains & timelines",
    helper: "Which alerts may be related?",
    desc: "Correlates distinct alerts sharing shared assets, user identities, temporal proximity, and escalating severity patterns.",
    iconName: "GitMerge",
    gradient: "from-purple-500/20 to-indigo-500/5",
    borderGlow: "group-hover:border-purple-500/60",
    accentColor: "purple",
  },
  {
    num: 4,
    id: "expected-vs-observed",
    name: "Expected vs Observed",
    tagline: "Operational playbook baseline vs recorded evidence",
    helper: "What should have happened vs what the evidence shows?",
    desc: "Compares mandatory operational response baselines against recorded case evidence to pinpoint protocol deviations requiring supervisory inquiry.",
    iconName: "Layers",
    gradient: "from-emerald-500/20 to-teal-500/5",
    borderGlow: "group-hover:border-emerald-500/60",
    accentColor: "emerald",
  },
  {
    num: 5,
    id: "peer-comparison",
    name: "Peer Comparison",
    tagline: "Cross-entity contextual behavioural benchmarking",
    helper: "How does this entity's operational behavior compare to peers?",
    desc: "Provides supervisory context across peer critical sector entities without reductive security scoring or composite rankings.",
    iconName: "BarChart3",
    gradient: "from-blue-500/20 to-indigo-500/5",
    borderGlow: "group-hover:border-blue-500/60",
    accentColor: "blue",
  },
  {
    num: 6,
    id: "evidence-traceability",
    name: "Evidence Traceability",
    tagline: "Audit-grade evidence linking & raw telemetry logs",
    helper: "Why did ARGUS produce this finding?",
    desc: "Direct audit chain from supervisory finding rationale down to primary telemetry records and raw immutable event logs.",
    iconName: "FileCheck",
    gradient: "from-rose-500/20 to-pink-500/5",
    borderGlow: "group-hover:border-rose-500/60",
    accentColor: "rose",
  },
];

export const VIEW_HASHES = {
  "home": "#home",
  "graph": "#graph",
  "execution-gaps": "#execution-gaps",
  "negative-space": "#negative-space",
  "incident-reconstruction": "#incident-reconstruction",
  "expected-vs-observed": "#expected-vs-observed",
  "peer-comparison": "#peer-comparison",
  "evidence-traceability": "#evidence-traceability",
  "ghost-replay": "#ghost-replay",
  "counterfactual": "#counterfactual",
  "assessment-graph": "#graph",
  "overview-legacy": "#peer-comparison",
};

export const HASH_TO_VIEW = {
  "#home": "graph",
  "#graph": "graph",
  "#review-queue": "graph",
  "#assessment-graph": "graph",
  "#execution-gaps": "execution-gaps",
  "#negative-space": "negative-space",
  "#incident-reconstruction": "incident-reconstruction",
  "#expected-vs-observed": "expected-vs-observed",
  "#peer-comparison": "peer-comparison",
  "#evidence-traceability": "evidence-traceability",
  "#ghost-replay": "ghost-replay",
  "#counterfactual": "counterfactual",
  "#overview": "peer-comparison",
  "": "graph",
  "#": "graph",
};

export const RULE_TRANSLATIONS = {
  "EG-01": {
    code: "EG-01",
    plainTitle: "Expected escalation may be missing",
    shortLabel: "Un-escalated serious alert",
    whatNoticed: "High or Critical severity alerts were closed without recorded supervisory escalation.",
    whyReview: "Unescalated serious alerts can allow active threats to persist behind apparently high closure metrics.",
    supervisorAction: "Verify whether these alerts required formal supervisory escalation and containment.",
    accent: "amber",
  },
  "EG-02": {
    code: "EG-02",
    plainTitle: "Possible case closed too quickly",
    shortLabel: "Possible premature closure",
    whatNoticed: "A serious alert was closed rapidly and other expected investigation evidence appears weak or missing.",
    whyReview: "Rapid closure alone is not problematic, but combined with minimal notes or absent escalation, it warrants supervisory verification.",
    supervisorAction: "Verify whether an adequate investigation occurred prior to closure approval.",
    accent: "red",
  },
  "EG-03": {
    code: "EG-03",
    plainTitle: "Investigation evidence may be too weak or repetitive",
    shortLabel: "Repetitive note / weak investigation",
    whatNoticed: "Multiple cases contain identical templated notes or minimal recorded diagnostic reasoning.",
    whyReview: "Templated notes suggest procedural rubber-stamping rather than genuine diagnostic analysis.",
    supervisorAction: "Review investigation quality and verify if analyst workload is forcing copy-paste closures.",
    accent: "amber",
  },
  "EG-04": {
    code: "EG-04",
    plainTitle: "Repeated similar alerts may indicate unremediated issue",
    shortLabel: "Repeated unremediated alerts",
    whatNoticed: "Multiple alerts of the same signature occurred on this asset within a short time window.",
    whyReview: "Recurring alerts suggest root causes are being closed without effective remediation.",
    supervisorAction: "Determine if root-cause remediation was completed or if alerts are being dismissed repeatedly.",
    accent: "orange",
  },
  "NS-01": {
    code: "NS-01",
    plainTitle: "Critical asset monitoring evidence void",
    shortLabel: "Critical asset monitoring void",
    whatNoticed: "Asset is classified as critical, but zero telemetry or alert evidence was recorded during the observation window.",
    whyReview: "Silence on a critical asset can indicate sensor failure, network misconfiguration, or deliberate disabling.",
    supervisorAction: "Verify physical and network telemetry collection status for this critical asset.",
    accent: "cyan",
  },
  "NS-02": {
    code: "NS-02",
    plainTitle: "Expected operational process evidence absent",
    shortLabel: "Expected process evidence absent",
    whatNoticed: "Designated core operational processes did not produce expected case, ticket, or supervisory log records.",
    whyReview: "Absence of expected records may indicate non-compliance with mandatory operational reporting mandates.",
    supervisorAction: "Audit operational shift logs to confirm whether the process occurred but escaped recording.",
    accent: "blue",
  },
  "IR-01": {
    code: "IR-01",
    plainTitle: "Candidate Incident — Potentially related alerts. Human verification required.",
    shortLabel: "Candidate Incident Correlation",
    whatNoticed: "Multiple alerts across distinct categories share common assets, identities, and progressive severity.",
    whyReview: "Fragmented alert handling can obscure multi-stage intrusion campaigns across operational shifts.",
    supervisorAction: "Initiate joint incident timeline review to confirm whether alerts represent a unified campaign.",
    accent: "purple",
  },
};

export const getRuleTranslation = (ruleCode) => {
  return RULE_TRANSLATIONS[ruleCode] || {
    code: ruleCode,
    plainTitle: `Supervisory Indicator ${ruleCode}`,
    shortLabel: ruleCode,
    whatNoticed: "Anomalous behavioural indicator detected in historical evidence.",
    whyReview: "Requires supervisory review to ensure operational protocol was satisfied.",
    supervisorAction: "Inspect underlying case and alert evidence records.",
    accent: "slate",
  };
};
